### ISSUE TITLE
Sample  does't work.

### ISSUE THREAD

**Issue by Anson1417** [ExtCore/ExtCore-Sample#4]
I download the code and run, but there is nothing showing.

I tried 
http://localhost:1234/ExtensionA
http://localhost:1234/Extension-A
http://localhost:1234/Extension-B

and i found in DiscoverAssemblies(), the path doesn't match "Extensions".

**Comment by DmitrySikorsky** [comment]
What is the value of 'path' variable in the DiscoverAssemblies()? Have you changed the config.json?

**Comment by DmitrySikorsky** [comment]
I've tested right now.
1. Downloaded the sample.
2. Opened with VS.
3. Waited.
4. Run.

It worked. I had 2 working URLs: / and /extension-b.

Please help me to find out what is the problem in your case. Thanks!

**Comment by Anson1417** [comment]
DmitrySikorsky , Thanks for you help, i found my the problem.

i need to rebuild the ProjectA and ProjectB first, as there are no dll files.

one more question, after i running the app, i want to rebuild the project and execute copy-extensions task, it says the file is locked.

**Comment by DmitrySikorsky** [comment]
You can't replace dll files of working application, because they are being executed by web server. You need to stop the web server first.

**Comment by Anson1417** [comment]
Yes, i known,  it is not so convenient under developing. If we can find a way to re-active the dll without stop the server, that will be better.

**Comment by DmitrySikorsky** [comment]
While developing just add direct references to your projects in main project. Without copying dlls to the folder. When the extensions are done, remove direct references (if you need this) and copy dlls.
