### ISSUE TITLE
Doesn't startup

### ISSUE THREAD

**Issue by bdparrish** [ExtCore/ExtCore-Sample#5]
The project starts up and builds with no errors or warnings, but immediately exits with code 0.

![extcore](https://cloud.githubusercontent.com/assets/720788/22706979/3074fffa-ed3f-11e6-9e1d-9027dacae357.gif)

**Comment by DmitrySikorsky** [comment]
Please try to publish the web application to some location and then execute following commands in the cmd:

1. cd 'path to the published application'
2. dotnet webapplication.dll

I think you will see the error message or message that you should open browser and navigate to localhost:1234.

I have never have the problem like in your video, so I would like to find out the reason. Thank you!

**Comment by bdparrish** [comment]
How do I publish to my localhost?  Can I just run a 'dotnet' command?

**Comment by DmitrySikorsky** [comment]
It should just work from visual studio, but in your case it doesn't. Maybe there is a better way to find the reason, but I would just publish to desktop (or any other folder) and run from that location using kestrel, without IIS Express. To publish just right click on the web app project and click Publish menu item, set folder and that's all.

**Comment by bdparrish** [comment]
I didn't have to publish.  Just ran `dotnet run` from the `project.json` folder and found what was causing the issue.  I had `1.1.0-preview1-*` installed and not `1.1.0`, so the dependency in `project.json` needed to be updated to reflect the right Microsoft.Net.App version or install the right version of `dotnet`, in my case I needed the latest Preview found [here](https://go.microsoft.com/fwlink/?LinkID=834981) - (1.0.0-preview2.1-003177).
