### ISSUE TITLE
Dynamic loading results in a null reference to ExtensionB

### ISSUE THREAD

**Issue by westonsoftware** [ExtCore/ExtCore-Sample#7]
If I run the sample with direct project references, it works great.
If I copy the .dll's to the Extensions folder, they appear to load fine, but the ExtensionB index view cannot be pulled up and results in a null reference.  (my own app is getting razor compile errors too)

I spent time trying to fix this here and in my app with no luck.  My best guess is that something isn't right with the default assembly loader using the latest version of Razor.

**Comment by DmitrySikorsky** [comment]
Hi @westonsoftware, thank you for your question.

Where is the null reference? Is it some service injected inside the view? Because I  don't think that resolving view itself may result in null reference.

**Comment by westonsoftware** [comment]
Hi, yeah, it happens here in the ExtensionB controller ...
```
NullReferenceException: Object reference not set to an instance of an object.
WebApplication.ExtensionB.Controllers.ExtensionBController.Index() in ExtensionBController.cs
line 24:
           return this.View(new IndexViewModelFactory().Create(this.storage.GetRepository<IItemRepository>().All()));
```

I also added my own test route to try and eliminate any database problems …
```
[HttpGet("test")]
public ActionResult Test()
{
      return this.View(new ItemViewModel { Name = "andy" } );
}
```

This code results in this error …
```
One or more compilation references may be missing. If you're seeing this in a published application, set 'CopyRefAssembliesToPublishDirectory' to true in your project file to ensure files in the refs directory are published.

The type or namespace name 'ViewModels' does not exist in the namespace 'WebApplication.ExtensionB' (are you missing an assembly reference?)
+
    public class _Views_ExtensionB_Test : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<WebApplication.ExtensionB.ViewModels.Shared.ItemViewModel>

```
It all runs fine when I reference the projects directly so I think it is an assembly loading problem.

**Comment by DmitrySikorsky** [comment]
I think this is because your project has dependency on something that is not present in your Extensions folder. For example, your extension A uses some B lib. You must copy B.dll (and all its dependencies) into your extension folder too in order it to be loaded.

**Comment by westonsoftware** [comment]
I'm using your project.  I would be curious to see if you get the same error when you run it.
--Andy

**Comment by DmitrySikorsky** [comment]
You can try any ExtCore sample app. There are many of them. You can remove direct dependencies on extension projects and copy their DLL into the extensions folder. BUT. It won't run if, for example, your ProjectName.SqlServer lib contains dependency on ExtCore.Data.EntityFramework.SqlServer and you neither add dependency on it to the main application nor copied ExtCore.Data.EntityFramework.SqlServer.dll to the extensions folder. DLL can't be loaded if any of its dependencies not present inside the extensions folder or inside the main app's dependencies. Simple.
