### ISSUE TITLE
Looping through Installed Extensions

### ISSUE THREAD

**Issue by davidbuckleyni** [ExtCore/ExtCore-Sample#8]
How would one provide a list to a customer that would show which plugins are enabled or disabled to the customer is their an example of that interface somewhere thanks excellent product been trying a few examples about ur is the easitet so far to get a mvc one loaded.

**Comment by DmitrySikorsky** [comment]
This feature (as well as views/styles/scripts designer) will be removed from version 2.0.0. Now we use Platformus on many (almost all) of our projects, and we never use this feature.

Platformus is CMS for developers, not for end users as I see now. Just to create simple backend for a website or a mobile app. Usually we create backend project with sections we need etc.

So it is very easy to install needed extensions before publish, we don't need an UI for that.
