### ISSUE TITLE
Issue not working in .net 5 

### ISSUE THREAD

**Issue by davidbuckleyni** [ExtCore/ExtCore-Sample#9]
I am using the rather excellent exCore to bring plugin functionallity to my app but I am getting the follow issue the controller is not being found.

    public class UseEndpointsAction : IUseEndpointsAction
    {
        public int Priority => 2000;

        public void Execute(IEndpointRouteBuilder endpointRouteBuilder, IServiceProvider serviceProvider)
        {
            endpointRouteBuilder.MapControllerRoute(name: "hello", pattern: "hello-b", defaults: new { controller = "Hello", action = "Index" });
        }
    }
    }
I have setup my end points in the class libary as directed by the excellent docs here  and samples https://github.com/ExtCore/ExtCore-Sample  and docs here  http://docs.extcore.net/en/latest/getting_started/index.html

However I am getting the following 

[![enter image description here][1]][1]

I Created the class file as well for the plugin 

    using ExtCore.Infrastructure;
    using System;

     namespace WareHouseCrm.PaymentProcesser.PayPalStandard
     {
        public class PayPalStandard : ExtensionBase
        {
            public override string Name => "PayPalStandard"; 
      }
    }

The controller file 

    namespace WareHouseCrm.PaymentProcesser.PayPalStandard.Controllers
     {
         public class HelloController :Controller
         {
 
           public IActionResult Index()
           {
            return View();
           }
          }
      }

And the view just a simple output Index.cshtml

    @{
       ViewData["Title"] = "Test";   
      }
     Test for the plugin this should come back

I have copied the file to the Extensions directory then started up the application also is their a way i can automate this to save me copying the file on every build for testing.

I have added the code in the startup file it suggested.

    private string extensionsPath;
    public Startup(IWebHostEnvironment webHostEnvironment, IConfiguration configuration) {
            Configuration = configuration;
            this.extensionsPath = webHostEnvironment.ContentRootPath + configuration["Extensions:Path"];
    }

Added the extension in services

    services.AddExtCore(this.extensionsPath);

and also in the configure section 

    app.UseExtCore();

My settings for completness

     "Extensions": {
    "Path": "\\Extensions",
    "IncludingSubpaths": true
   },

Showing project structure 

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/OpwT8.png
  [2]: https://i.stack.imgur.com/wh9qk.png

**Comment by DmitrySikorsky** [comment]
Hi! Considering the error message, your controller is found, but it can't find the views. So just put the views in the correct location and it should work.
